import { NextResponse, type NextRequest } from "next/server";
import ExcelJS from "exceljs";
import Papa from "papaparse";
import { getSessionUser } from "@/lib/auth/session";
import { getPeriods, getSettings } from "@/lib/data/lookups";
import { getAdminAnalytics, periodFilterLabel, resolveAnalyticsFilters } from "@/lib/analytics/admin";
import { buildReportSections, safeCell } from "@/lib/analytics/report-sections";
import { logActivity } from "@/lib/activity";

export async function GET(request: NextRequest) {
  const user = await getSessionUser();
  if (!user || user.role !== "admin" || user.mustChangePassword) {
    return NextResponse.json({ error: "Not authorized" }, { status: 403 });
  }
  const sp = request.nextUrl.searchParams;
  const format = sp.get("format") === "xlsx" ? "xlsx" : "csv";
  const params = Object.fromEntries([...sp.entries()].map(([k, v]) => [k, v.slice(0, 100)]));
  const [periods, settings] = await Promise.all([getPeriods(), getSettings()]);
  const f = resolveAnalyticsFilters(params, periods);
  const a = await getAdminAnalytics(f);
  const sections = buildReportSections(a, settings.rating_scale.map((s) => s.label));
  const generated = new Date();
  const header: [string, string][] = [
    ["Institution", settings.institution_name],
    ["Report", "ASSCAT iRATE – Faculty Evaluation Report"],
    ["Period", periodFilterLabel(f)],
    ["Filters", ["department", "program", "faculty", "subject"].filter((x) => f[x as keyof typeof f]).join(", ") || "None"],
    ["Generated", generated.toLocaleString("en-PH", { timeZone: "Asia/Manila" })],
    ["Generated by", user.displayName],
  ];
  const stamp = generated.toISOString().slice(0, 10);

  await logActivity({ user, module: "Reports", action: `Exported report (${format.toUpperCase()})`, description: periodFilterLabel(f) });

  if (format === "csv") {
    const rows: (string | number)[][] = header.map(([k, v]) => [k, safeCell(v)]);
    for (const s of sections) {
      rows.push([], [s.title], s.columns, ...s.rows.map((r) => r.map(safeCell)));
    }
    const csv = "﻿" + Papa.unparse(rows);
    return new NextResponse(csv, {
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="asscat-irate-report-${stamp}.csv"`,
        "Cache-Control": "no-store",
      },
    });
  }

  const wb = new ExcelJS.Workbook();
  wb.creator = "ASSCAT iRATE";
  wb.created = generated;
  for (const s of sections) {
    const ws = wb.addWorksheet(s.sheet);
    for (const [k, v] of header) ws.addRow([k, safeCell(v)]).getCell(1).font = { bold: true };
    ws.addRow([]);
    const title = ws.addRow([s.title]);
    title.font = { bold: true, size: 13, color: { argb: "FF1C7430" } };
    const head = ws.addRow(s.columns);
    head.eachCell((c) => {
      c.font = { bold: true, color: { argb: "FFFFFFFF" } };
      c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF28A745" } };
    });
    for (const r of s.rows) ws.addRow(r.map(safeCell));
    ws.columns.forEach((col, i) => { col.width = Math.min(60, Math.max(12, ...s.rows.map((r) => String(r[i] ?? "").length + 2), (s.columns[i]?.length ?? 0) + 2)); });
  }
  const buffer = await wb.xlsx.writeBuffer();
  return new NextResponse(buffer as ArrayBuffer, {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": `attachment; filename="asscat-irate-report-${stamp}.xlsx"`,
      "Cache-Control": "no-store",
    },
  });
}
