// AUTO-GENERATED by scripts/gen-db-types.py from supabase/migrations. Do not edit by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      academic_periods: {
        Row: {
          id: string;
          start_year: number;
          semester: number;
          open_at: string;
          close_at: string;
          is_current: boolean;
          results_released_at: string | null;
          school_year: string | null;
          label: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          start_year: number;
          semester: number;
          open_at: string;
          close_at: string;
          is_current?: boolean;
          results_released_at?: string | null;
          school_year?: never;
          label?: never;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          start_year?: number;
          semester?: number;
          open_at?: string;
          close_at?: string;
          is_current?: boolean;
          results_released_at?: string | null;
          school_year?: never;
          label?: never;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      activity_logs: {
        Row: {
          id: number;
          user_id: string | null;
          user_name: string | null;
          role: Database["public"]["Enums"]["app_role"] | null;
          action: string;
          module: string;
          description: string | null;
          entity_type: string | null;
          entity_id: string | null;
          ip_address: string | null;
          user_agent: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: never;
          user_id?: string | null;
          user_name?: string | null;
          role?: Database["public"]["Enums"]["app_role"] | null;
          action: string;
          module: string;
          description?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: never;
          user_id?: string | null;
          user_name?: string | null;
          role?: Database["public"]["Enums"]["app_role"] | null;
          action?: string;
          module?: string;
          description?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      departments: {
        Row: {
          id: string;
          code: string;
          name: string;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          name: string;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          name?: string;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      evaluation_answers: {
        Row: {
          id: string;
          attempt_id: string;
          question_id: string;
          category_id: string | null;
          rating: number;
          scale_max: number;
          rating_label: string | null;
          category_name: string;
          question_title: string;
          question_text: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          attempt_id: string;
          question_id: string;
          category_id?: string | null;
          rating: number;
          scale_max?: number;
          rating_label?: string | null;
          category_name: string;
          question_title: string;
          question_text: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          attempt_id?: string;
          question_id?: string;
          category_id?: string | null;
          rating?: number;
          scale_max?: number;
          rating_label?: string | null;
          category_name?: string;
          question_title?: string;
          question_text?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "evaluation_answers_attempt_id_fkey";
            columns: ["attempt_id"];
            isOneToOne: false;
            referencedRelation: "evaluation_attempts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "evaluation_answers_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "question_categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "evaluation_answers_question_id_fkey";
            columns: ["question_id"];
            isOneToOne: false;
            referencedRelation: "questions";
            referencedColumns: ["id"];
          },
        ];
      };
      evaluation_attempts: {
        Row: {
          id: string;
          offering_id: string;
          student_id: string;
          academic_period_id: string;
          status: Database["public"]["Enums"]["evaluation_status"];
          started_at: string;
          submitted_at: string | null;
          average_rating: number | null;
          source: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          offering_id: string;
          student_id: string;
          academic_period_id: string;
          status?: Database["public"]["Enums"]["evaluation_status"];
          started_at?: string;
          submitted_at?: string | null;
          average_rating?: number | null;
          source?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          offering_id?: string;
          student_id?: string;
          academic_period_id?: string;
          status?: Database["public"]["Enums"]["evaluation_status"];
          started_at?: string;
          submitted_at?: string | null;
          average_rating?: number | null;
          source?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "evaluation_attempts_enrollment_fkey";
            columns: ["offering_id", "student_id"];
            isOneToOne: false;
            referencedRelation: "subject_enrollments";
            referencedColumns: ["offering_id", "student_id"];
          },
          {
            foreignKeyName: "evaluation_attempts_offering_period_fkey";
            columns: ["offering_id", "academic_period_id"];
            isOneToOne: false;
            referencedRelation: "subject_offerings";
            referencedColumns: ["id", "academic_period_id"];
          },
        ];
      };
      evaluation_comments: {
        Row: {
          id: string;
          attempt_id: string;
          comment: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          attempt_id: string;
          comment: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          attempt_id?: string;
          comment?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "evaluation_comments_attempt_id_fkey";
            columns: ["attempt_id"];
            isOneToOne: true;
            referencedRelation: "evaluation_attempts";
            referencedColumns: ["id"];
          },
        ];
      };
      faculty: {
        Row: {
          id: string;
          profile_id: string | null;
          faculty_number: string;
          first_name: string;
          middle_name: string | null;
          last_name: string;
          email: string;
          birthday: string | null;
          date_started: string | null;
          program_id: string;
          department_id: string;
          photo_path: string | null;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id?: string | null;
          faculty_number: string;
          first_name: string;
          middle_name?: string | null;
          last_name: string;
          email: string;
          birthday?: string | null;
          date_started?: string | null;
          program_id: string;
          department_id: string;
          photo_path?: string | null;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string | null;
          faculty_number?: string;
          first_name?: string;
          middle_name?: string | null;
          last_name?: string;
          email?: string;
          birthday?: string | null;
          date_started?: string | null;
          program_id?: string;
          department_id?: string;
          photo_path?: string | null;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "faculty_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: true;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "faculty_program_department_fkey";
            columns: ["program_id", "department_id"];
            isOneToOne: false;
            referencedRelation: "programs";
            referencedColumns: ["id", "department_id"];
          },
        ];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          message: string;
          type: string;
          link: string | null;
          dedupe_key: string | null;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          message: string;
          type?: string;
          link?: string | null;
          dedupe_key?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          message?: string;
          type?: string;
          link?: string | null;
          dedupe_key?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          role: Database["public"]["Enums"]["app_role"];
          email: string;
          first_name: string | null;
          middle_name: string | null;
          last_name: string | null;
          avatar_path: string | null;
          is_active: boolean;
          must_change_password: boolean;
          last_login_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          role: Database["public"]["Enums"]["app_role"];
          email: string;
          first_name?: string | null;
          middle_name?: string | null;
          last_name?: string | null;
          avatar_path?: string | null;
          is_active?: boolean;
          must_change_password?: boolean;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          role?: Database["public"]["Enums"]["app_role"];
          email?: string;
          first_name?: string | null;
          middle_name?: string | null;
          last_name?: string | null;
          avatar_path?: string | null;
          is_active?: boolean;
          must_change_password?: boolean;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      programs: {
        Row: {
          id: string;
          code: string;
          name: string;
          department_id: string;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          name: string;
          department_id: string;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          name?: string;
          department_id?: string;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "programs_department_id_fkey";
            columns: ["department_id"];
            isOneToOne: false;
            referencedRelation: "departments";
            referencedColumns: ["id"];
          },
        ];
      };
      question_categories: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          sort_order: number;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      questions: {
        Row: {
          id: string;
          category_id: string;
          title: string;
          content: string;
          sort_order: number;
          is_required: boolean;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          category_id: string;
          title: string;
          content: string;
          sort_order?: number;
          is_required?: boolean;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          category_id?: string;
          title?: string;
          content?: string;
          sort_order?: number;
          is_required?: boolean;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "questions_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "question_categories";
            referencedColumns: ["id"];
          },
        ];
      };
      students: {
        Row: {
          id: string;
          profile_id: string | null;
          student_number: string;
          first_name: string;
          middle_name: string | null;
          last_name: string;
          email: string;
          program_id: string;
          year_level_id: string;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id?: string | null;
          student_number: string;
          first_name: string;
          middle_name?: string | null;
          last_name: string;
          email: string;
          program_id: string;
          year_level_id: string;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string | null;
          student_number?: string;
          first_name?: string;
          middle_name?: string | null;
          last_name?: string;
          email?: string;
          program_id?: string;
          year_level_id?: string;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "students_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: true;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "students_program_id_fkey";
            columns: ["program_id"];
            isOneToOne: false;
            referencedRelation: "programs";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "students_year_level_id_fkey";
            columns: ["year_level_id"];
            isOneToOne: false;
            referencedRelation: "year_levels";
            referencedColumns: ["id"];
          },
        ];
      };
      subject_enrollments: {
        Row: {
          id: string;
          offering_id: string;
          student_id: string;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          offering_id: string;
          student_id: string;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          offering_id?: string;
          student_id?: string;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "subject_enrollments_offering_id_fkey";
            columns: ["offering_id"];
            isOneToOne: false;
            referencedRelation: "subject_offerings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subject_enrollments_student_id_fkey";
            columns: ["student_id"];
            isOneToOne: false;
            referencedRelation: "students";
            referencedColumns: ["id"];
          },
        ];
      };
      subject_offerings: {
        Row: {
          id: string;
          subject_id: string;
          faculty_id: string;
          program_id: string;
          academic_period_id: string;
          section: string;
          deleted_at: string | null;
          deleted_by: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          subject_id: string;
          faculty_id: string;
          program_id: string;
          academic_period_id: string;
          section?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          subject_id?: string;
          faculty_id?: string;
          program_id?: string;
          academic_period_id?: string;
          section?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "subject_offerings_academic_period_id_fkey";
            columns: ["academic_period_id"];
            isOneToOne: false;
            referencedRelation: "academic_periods";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subject_offerings_faculty_id_fkey";
            columns: ["faculty_id"];
            isOneToOne: false;
            referencedRelation: "faculty";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subject_offerings_program_id_fkey";
            columns: ["program_id"];
            isOneToOne: false;
            referencedRelation: "programs";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subject_offerings_subject_id_fkey";
            columns: ["subject_id"];
            isOneToOne: false;
            referencedRelation: "subjects";
            referencedColumns: ["id"];
          },
        ];
      };
      subjects: {
        Row: {
          id: string;
          code: string;
          title: string;
          description: string | null;
          units: number | null;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          title: string;
          description?: string | null;
          units?: number | null;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          title?: string;
          description?: string | null;
          units?: number | null;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      system_settings: {
        Row: {
          key: string;
          value: Json;
          description: string | null;
          is_public: boolean;
          updated_by: string | null;
          updated_at: string;
        };
        Insert: {
          key: string;
          value: Json;
          description?: string | null;
          is_public?: boolean;
          updated_by?: string | null;
          updated_at?: string;
        };
        Update: {
          key?: string;
          value?: Json;
          description?: string | null;
          is_public?: boolean;
          updated_by?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      year_levels: {
        Row: {
          id: string;
          name: string;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      activity_log_overview: {
        Row: {
          id: number | null;
          user_id: string | null;
          user_name: string | null;
          role: Database["public"]["Enums"]["app_role"] | null;
          action: string | null;
          module: string | null;
          description: string | null;
          entity_type: string | null;
          entity_id: string | null;
          ip_address: string | null;
          user_agent: string | null;
          metadata: Json | null;
          created_at: string | null;
          search_text: string | null;
        };
        Relationships: [];
      };
      category_overview: {
        Row: {
          id: string | null;
          name: string | null;
          description: string | null;
          sort_order: number | null;
          is_active: boolean | null;
          created_by: string | null;
          created_at: string | null;
          updated_at: string | null;
          question_count: number | null;
          active_question_count: number | null;
          search_text: string | null;
        };
        Relationships: [];
      };
      department_overview: {
        Row: {
          id: string | null;
          code: string | null;
          name: string | null;
          is_active: boolean | null;
          created_by: string | null;
          created_at: string | null;
          updated_at: string | null;
          program_count: number | null;
          search_text: string | null;
        };
        Relationships: [];
      };
      enrollment_overview: {
        Row: {
          id: string | null;
          offering_id: string | null;
          student_id: string | null;
          created_at: string | null;
          student_number: string | null;
          student_name: string | null;
          sort_name: string | null;
          student_is_active: boolean | null;
          program_code: string | null;
          year_level_name: string | null;
          year_level_order: number | null;
          attempt_id: string | null;
          evaluation_status: string | null;
          average_rating: number | null;
          submitted_at: string | null;
          started_at: string | null;
          search_text: string | null;
        };
        Relationships: [];
      };
      faculty_overview: {
        Row: {
          id: string | null;
          profile_id: string | null;
          faculty_number: string | null;
          first_name: string | null;
          middle_name: string | null;
          last_name: string | null;
          email: string | null;
          birthday: string | null;
          date_started: string | null;
          program_id: string | null;
          department_id: string | null;
          photo_path: string | null;
          is_active: boolean | null;
          created_by: string | null;
          created_at: string | null;
          updated_at: string | null;
          full_name: string | null;
          sort_name: string | null;
          program_code: string | null;
          program_name: string | null;
          department_code: string | null;
          department_name: string | null;
          years_of_service: number | null;
          age: number | null;
          search_text: string | null;
        };
        Relationships: [];
      };
      offering_overview: {
        Row: {
          id: string | null;
          academic_period_id: string | null;
          section: string | null;
          subject_id: string | null;
          faculty_id: string | null;
          program_id: string | null;
          created_at: string | null;
          subject_code: string | null;
          subject_title: string | null;
          faculty_number: string | null;
          faculty_name: string | null;
          faculty_email: string | null;
          faculty_photo_path: string | null;
          program_code: string | null;
          program_name: string | null;
          department_id: string | null;
          department_code: string | null;
          department_name: string | null;
          period_label: string | null;
          school_year: string | null;
          semester: number | null;
          start_year: number | null;
          open_at: string | null;
          close_at: string | null;
          enrolled_count: number | null;
          completed_count: number | null;
          in_progress_count: number | null;
          progress_pct: number | null;
          average_rating: number | null;
          search_text: string | null;
        };
        Relationships: [];
      };
      period_overview: {
        Row: {
          id: string | null;
          start_year: number | null;
          semester: number | null;
          open_at: string | null;
          close_at: string | null;
          is_current: boolean | null;
          results_released_at: string | null;
          school_year: string | null;
          label: string | null;
          created_by: string | null;
          created_at: string | null;
          updated_at: string | null;
          status: string | null;
        };
        Relationships: [];
      };
      program_overview: {
        Row: {
          id: string | null;
          code: string | null;
          name: string | null;
          department_id: string | null;
          is_active: boolean | null;
          created_by: string | null;
          created_at: string | null;
          updated_at: string | null;
          department_code: string | null;
          department_name: string | null;
          search_text: string | null;
        };
        Relationships: [];
      };
      question_overview: {
        Row: {
          id: string | null;
          category_id: string | null;
          title: string | null;
          content: string | null;
          sort_order: number | null;
          is_required: boolean | null;
          is_active: boolean | null;
          created_by: string | null;
          created_at: string | null;
          updated_at: string | null;
          category_name: string | null;
          category_is_active: boolean | null;
          category_sort_order: number | null;
          is_used: boolean | null;
          search_text: string | null;
        };
        Relationships: [];
      };
      student_overview: {
        Row: {
          id: string | null;
          profile_id: string | null;
          student_number: string | null;
          first_name: string | null;
          middle_name: string | null;
          last_name: string | null;
          email: string | null;
          program_id: string | null;
          year_level_id: string | null;
          is_active: boolean | null;
          created_by: string | null;
          created_at: string | null;
          updated_at: string | null;
          full_name: string | null;
          sort_name: string | null;
          program_code: string | null;
          program_name: string | null;
          department_id: string | null;
          department_code: string | null;
          department_name: string | null;
          year_level_name: string | null;
          year_level_order: number | null;
          search_text: string | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      admin_analytics: {
        Args: {
          p_period_id?: string;
          p_start_year?: number;
          p_semester?: number;
          p_department_id?: string;
          p_program_id?: string;
          p_faculty_id?: string;
          p_subject_id?: string;
        };
        Returns: Json;
      };
      admin_import_course_rows: {
        Args: {
          p_rows: Json;
        };
        Returns: Json;
      };
      admin_import_evaluation_rows: {
        Args: {
          p_rows: Json;
        };
        Returns: Json;
      };
      admin_release_results: {
        Args: {
          p_period_id: string;
          p_release: boolean;
        };
        Returns: undefined;
      };
      admin_reset_evaluation: {
        Args: {
          p_attempt_id: string;
        };
        Returns: Json;
      };
      admin_set_current_period: {
        Args: {
          p_period_id: string;
        };
        Returns: undefined;
      };
      complete_password_change: {
        Args: never;
        Returns: undefined;
      };
      current_app_role: {
        Args: never;
        Returns: Database["public"]["Enums"]["app_role"];
      };
      current_faculty_id: {
        Args: never;
        Returns: string;
      };
      current_student_id: {
        Args: never;
        Returns: string;
      };
      format_person_name: {
        Args: {
          p_first: string;
          p_middle: string;
          p_last: string;
        };
        Returns: string;
      };
      generate_scheduled_notifications: {
        Args: never;
        Returns: number;
      };
      get_evaluation_form: {
        Args: {
          p_offering_id: string;
        };
        Returns: Json;
      };
      get_faculty_analytics: {
        Args: {
          p_period_id?: string;
          p_offering_id?: string;
        };
        Returns: Json;
      };
      get_faculty_offerings: {
        Args: {
          p_period_id?: string;
        };
        Returns: {
          offering_id: string;
          subject_code: string;
          subject_title: string;
          section: string;
          program_code: string;
          period_id: string;
          period_label: string;
          school_year: string;
          semester: number;
          is_current: boolean;
          enrolled: number;
          completed: number;
          results_visible: boolean;
          meets_threshold: boolean;
          average: number;
        }[];
      };
      get_offering_results: {
        Args: {
          p_offering_id: string;
        };
        Returns: Json;
      };
      get_setting: {
        Args: {
          p_key: string;
        };
        Returns: Json;
      };
      get_student_evaluations: {
        Args: {
          p_period_id?: string;
        };
        Returns: {
          offering_id: string;
          subject_code: string;
          subject_title: string;
          section: string;
          faculty_name: string;
          faculty_photo_path: string;
          period_id: string;
          period_label: string;
          open_at: string;
          close_at: string;
          status: string;
          started_at: string;
          submitted_at: string;
        }[];
      };
      get_student_periods: {
        Args: never;
        Returns: {
          id: string;
          label: string;
          start_year: number;
          semester: number;
          is_current: boolean;
        }[];
      };
      is_admin: {
        Args: never;
        Returns: boolean;
      };
      min_respondents: {
        Args: never;
        Returns: number;
      };
      period_status: {
        Args: {
          p_open: string;
          p_close: string;
        };
        Returns: string;
      };
      results_visible: {
        Args: {
          p_period_id: string;
        };
        Returns: boolean;
      };
      save_evaluation_progress: {
        Args: {
          p_offering_id: string;
          p_answers: Json;
          p_comment?: string;
        };
        Returns: Json;
      };
      submit_evaluation: {
        Args: {
          p_offering_id: string;
          p_answers: Json;
          p_comment?: string;
        };
        Returns: Json;
      };
      touch_last_login: {
        Args: never;
        Returns: undefined;
      };
    };
    Enums: {
      app_role: "admin" | "faculty" | "student";
      evaluation_status: "in_progress" | "completed";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];
export type Views<T extends keyof PublicSchema["Views"]> = PublicSchema["Views"][T]["Row"];
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T];
export type Functions<T extends keyof PublicSchema["Functions"]> = PublicSchema["Functions"][T];
